# Generated by Django 2.2.6 on 2019-11-29 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categorie name')),
                ('slug', models.SlugField(help_text='Automatiquement formé à partir du titre.', verbose_name='Référence')),
            ],
            options={
                'verbose_name_plural': 'catégories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(help_text='Automatiquement formé à partir du titre.', max_length=100, unique_for_date='publish', verbose_name='lien url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image associée')),
                ('body', models.TextField(blank=True, help_text='Utilisez la syntaxe HTML.', null=True, verbose_name='Contenu HTML')),
                ('counter', models.PositiveIntegerField(default=0)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='blog.Categorie', verbose_name='Catégorie(s)')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-publish',),
                'get_latest_by': 'publish',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Regions')),
            ],
            options={
                'verbose_name_plural': 'regions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='regions',
            field=models.ManyToManyField(to='blog.Regions', verbose_name='Régions'),
        ),
    ]
